apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: keyvault-secrets-provider
    labels:
        app: testapp
spec:
    provider: azure
    parameters:
        usePodIdentity: "false"
        useVMManagedIdentity: "true"
        userAssignedIdentityID: 21335769-d64b-4127-a629-f7b0c30b9ef1
        tenantId: dcb58767-2d57-462f-82d5-552df1c47ccb
        keyvaultName: keyvaultsamplek8s
        objects: |
            array:
              - |
                objectName: Sample
                objectType: secret
