---
# Source: testapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: testapp
  labels:
    helm.sh/chart: testapp-0.1.0
    app.kubernetes.io/name: testapp
    app.kubernetes.io/instance: testapp
    app.kubernetes.io/version: "2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: testapp
    app.kubernetes.io/instance: testapp
