---
# Source: testapp/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapp
  labels:
    helm.sh/chart: testapp-0.1.0
    app.kubernetes.io/name: testapp
    app.kubernetes.io/instance: testapp
    app.kubernetes.io/version: "2.0"
    app.kubernetes.io/managed-by: Helm
